{{ config(materialized='view') }}

-- Typed, snake_cased passthrough of FRAUD.RAW.RAW_IDENTITY.
-- No filtering, no business logic, no joins.

SELECT
    CAST("TransactionID" AS NUMBER(38,0)) AS transaction_id,
    CAST("id_01" AS FLOAT) AS id_01,
    CAST("id_02" AS FLOAT) AS id_02,
    CAST("id_03" AS FLOAT) AS id_03,
    CAST("id_04" AS FLOAT) AS id_04,
    CAST("id_05" AS FLOAT) AS id_05,
    CAST("id_06" AS FLOAT) AS id_06,
    CAST("id_07" AS FLOAT) AS id_07,
    CAST("id_08" AS FLOAT) AS id_08,
    CAST("id_09" AS FLOAT) AS id_09,
    CAST("id_10" AS FLOAT) AS id_10,
    CAST("id_11" AS FLOAT) AS id_11,
    CAST("id_12" AS VARCHAR) AS id_12,
    CAST("id_13" AS FLOAT) AS id_13,
    CAST("id_14" AS FLOAT) AS id_14,
    CAST("id_15" AS VARCHAR) AS id_15,
    CAST("id_16" AS VARCHAR) AS id_16,
    CAST("id_17" AS FLOAT) AS id_17,
    CAST("id_18" AS FLOAT) AS id_18,
    CAST("id_19" AS FLOAT) AS id_19,
    CAST("id_20" AS FLOAT) AS id_20,
    CAST("id_21" AS FLOAT) AS id_21,
    CAST("id_22" AS FLOAT) AS id_22,
    CAST("id_23" AS VARCHAR) AS id_23,
    CAST("id_24" AS FLOAT) AS id_24,
    CAST("id_25" AS FLOAT) AS id_25,
    CAST("id_26" AS FLOAT) AS id_26,
    CAST("id_27" AS VARCHAR) AS id_27,
    CAST("id_28" AS VARCHAR) AS id_28,
    CAST("id_29" AS VARCHAR) AS id_29,
    CAST("id_30" AS VARCHAR) AS id_30,
    CAST("id_31" AS VARCHAR) AS id_31,
    CAST("id_32" AS FLOAT) AS id_32,
    CAST("id_33" AS VARCHAR) AS id_33,
    CAST("id_34" AS VARCHAR) AS id_34,
    CAST("id_35" AS VARCHAR) AS id_35,
    CAST("id_36" AS VARCHAR) AS id_36,
    CAST("id_37" AS VARCHAR) AS id_37,
    CAST("id_38" AS VARCHAR) AS id_38,
    CAST("DeviceType" AS VARCHAR) AS device_type,
    CAST("DeviceInfo" AS VARCHAR) AS device_info
FROM {{ source('raw', 'RAW_IDENTITY') }}
