"""Train, calibrate, price the decision, and verify the warehouse layer.

Usage: python src/model.py {verify|train|decide|all}

No class rebalancing anywhere: the decision layer prices thresholds off
calibrated probabilities, and resampling distorts that scale.
"""

import json
import sys
from pathlib import Path

import joblib
import lightgbm as lgb
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.calibration import CalibratedClassifierCV, calibration_curve
from sklearn.frozen import FrozenEstimator
from sklearn.metrics import average_precision_score, brier_score_loss, roc_auc_score

sys.path.insert(0, str(Path(__file__).resolve().parent))
import core
from core import COSTS, MODELS, REPORTS, Report

VERIFY_MD = REPORTS / "verification.md"
RESULTS_MD = REPORTS / "stage1_results.md"

EXCLUDE = {"transaction_id", "account_id", "txn_day", "transaction_dt",
           "is_fraud", "prev_transaction_dt"}

BASELINE = {"n_features": 437, "train_pr_auc": 0.879783, "test_pr_auc_raw": 0.508558,
            "test_pr_auc_cal": 0.490119, "test_roc_auc_raw": 0.886324,
            "test_brier_raw": 0.022956, "test_brier_cal": 0.022980}

C_BEFORE, C_AFTER = "#2a78d6", "#eb6834"
C_OPT, C_NAIVE = "#1baf7a", "#eb6834"
INK, INK_2, GRIDC, SURFACE = "#0b0b0b", "#52514e", "#d9d8d2", "#fcfcfb"


def style(ax, title, xlabel, ylabel):
    ax.set_facecolor(SURFACE)
    ax.set_xlabel(xlabel, color=INK_2, fontsize=10)
    ax.set_ylabel(ylabel, color=INK_2, fontsize=10)
    ax.set_title(title, color=INK, fontsize=12, weight="bold", loc="left", pad=12)
    ax.grid(True, color=GRIDC, lw=0.8, alpha=0.7)
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)
    for s in ("left", "bottom"):
        ax.spines[s].set_color(GRIDC)
    ax.tick_params(colors=INK_2, labelsize=9)


# --------------------------------------------------------------------------- #
# verify
# --------------------------------------------------------------------------- #

def verify():
    R = Report(VERIFY_MD)
    conn = core.connect()
    cur = conn.cursor()
    flags = []
    q = core.query

    R("# Stage 1 verification"); R()
    R("Generated by `src/model.py verify`, `src/model.py train`, "
      "`src/model.py decide`."); R()
    R("## Part 1: dbt"); R(); R("### Row counts"); R()
    rc = q(cur, """
        SELECT 'fct_transactions' AS model, COUNT(*) AS n_rows FROM MARTS.FCT_TRANSACTIONS
        UNION ALL SELECT 'stg_transactions', COUNT(*) FROM STAGING.STG_TRANSACTIONS
        UNION ALL SELECT 'stg_identity',     COUNT(*) FROM STAGING.STG_IDENTITY
        UNION ALL SELECT 'dim_accounts',     COUNT(*) FROM MARTS.DIM_ACCOUNTS""")
    rc["N_ROWS"] = rc["N_ROWS"].astype(int)
    R.table(rc); R()
    n = int(rc.loc[rc.MODEL == "fct_transactions", "N_ROWS"].iloc[0])
    R(f"fct_transactions = {n:,}, expected 590,540 -> **{'PASS' if n == 590540 else 'FAIL'}**")
    if n != 590540:
        flags.append(f"fct row count {n}")
    R()

    R("### Account proxy"); R()
    ad = q(cur, """
        SELECT COUNT(*) AS distinct_accounts, MIN(txn_count) AS min_txns,
               MEDIAN(txn_count) AS median_txns, ROUND(AVG(txn_count),4) AS mean_txns,
               PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY txn_count) AS p95_txns,
               MAX(txn_count) AS max_txns
        FROM MARTS.DIM_ACCOUNTS""")
    R.table(ad.T.reset_index().rename(columns={"index": "metric", 0: "value"}))
    med = float(ad["MEDIAN_TXNS"].iloc[0]); R()
    if med <= 1:
        R(f"**FLAG RAISED: median transactions per account is {med}.**"); R()
        R("The tripwire measures the wrong population. 57.5% of accounts are cards "
          "seen once in 182 days. The median *transaction* sits in an account of 5, "
          "and 78.8% of transactions are in multi-transaction accounts, so the proxy "
          "does group. The 21.2% in singleton accounts never get prior-window history.")
        flags.append(f"median txns per account = {med} (transaction-weighted median is 5)")
    R()
    tw = q(cur, """
        SELECT MEDIAN(txn_count) AS txn_weighted_median, ROUND(AVG(txn_count),4) AS txn_weighted_mean,
               ROUND(100.0*COUNT_IF(txn_count>1)/COUNT(*),2) AS pct_txns_in_multi
        FROM MARTS.FCT_TRANSACTIONS f JOIN MARTS.DIM_ACCOUNTS d USING (account_id)""")
    R.table(tw.T.reset_index().rename(columns={"index": "metric", 0: "value"})); R()
    hist = q(cur, """
        SELECT CASE WHEN txn_count=1 THEN '1' WHEN txn_count BETWEEN 2 AND 4 THEN '2-4'
                    WHEN txn_count BETWEEN 5 AND 9 THEN '5-9'
                    WHEN txn_count BETWEEN 10 AND 49 THEN '10-49' ELSE '50+' END AS bucket,
               COUNT(*) AS accounts, SUM(txn_count) AS transactions
        FROM MARTS.DIM_ACCOUNTS GROUP BY 1 ORDER BY MIN(txn_count)""")
    hist["PCT_ACCOUNTS"] = (hist.ACCOUNTS / hist.ACCOUNTS.sum() * 100).round(2)
    hist["PCT_TRANSACTIONS"] = (hist.TRANSACTIONS / hist.TRANSACTIONS.sum() * 100).round(2)
    R.table(hist); R()

    R("### Degraded account keys"); R()
    R.table(q(cur, """
        SELECT account_key_tier, COUNT(*) AS n_rows,
               ROUND(100.0*COUNT(*)/SUM(COUNT(*)) OVER (),4) AS pct
        FROM MARTS.FCT_TRANSACTIONS GROUP BY 1 ORDER BY 2 DESC"""))
    R.table(q(cur, """
        SELECT COUNT_IF(is_degraded_key) AS degraded_rows,
               ROUND(100.0*COUNT_IF(is_degraded_key)/COUNT(*),4) AS degraded_pct
        FROM MARTS.FCT_TRANSACTIONS""")); R()

    R("### Null rate, engineered features"); R()
    feats = ["log_amount", "prior_txn_count", "prior_amt_sum", "prior_amt_mean",
             "txn_count_1h", "txn_count_24h", "txn_count_7d", "prev_transaction_dt",
             "seconds_since_prev_txn", "amt_to_prior_mean_ratio", "txn_hour",
             "txn_dow", "has_identity", "account_id", "is_degraded_key"]
    sel = ",\n".join(f"ROUND(100.0*COUNT_IF({f} IS NULL)/COUNT(*),4) AS {f}" for f in feats)
    nr = q(cur, f"SELECT {sel} FROM MARTS.FCT_TRANSACTIONS").T.reset_index()
    nr.columns = ["feature", "null_pct"]
    nr["null_pct"] = nr["null_pct"].astype(float)
    nr["flag"] = np.where(nr.null_pct > 50, "OVER 50%", "")
    R.table(nr); R()
    over = nr[nr.null_pct > 50]
    if len(over):
        R(f"**FLAG: {len(over)} feature(s) above 50% null: {', '.join(over.feature)}**")
        flags.append(f"features over 50% null: {list(over.feature)}")
    else:
        R("No engineered feature exceeds 50% null.")
    R()
    R("Prior-window features are null for each account's first transaction, "
      "217,850 of 590,540 rows (36.89%). That is what a frame ending at "
      "`1 PRECEDING` must produce."); R()

    R("### Passthrough blocks added in the refinement pass"); R()
    R("Passthrough, not engineered, so the 50% rule is reported separately. "
      "Identity columns are null for the 75.6% of transactions with no matching "
      "identity row, which is why `has_identity` is itself a feature."); R()
    R.table(q(cur, """
        WITH n AS (SELECT COUNT(*) AS t FROM MARTS.FCT_TRANSACTIONS)
        SELECT 'V block (V1-V339)' AS block, 339 AS columns,
               ROUND(100.0*COUNT_IF(v1 IS NULL)/MAX(t),4) AS example_null_pct
        FROM MARTS.FCT_TRANSACTIONS, n
        UNION ALL SELECT 'identity (id_01-id_38, device_*)', 40,
               ROUND(100.0*COUNT_IF(id_01 IS NULL)/MAX(t),4)
        FROM MARTS.FCT_TRANSACTIONS, n""")); R()

    R("### Identity coverage and fraud rate"); R()
    cov = q(cur, """
        SELECT ROUND(100.0*COUNT_IF(has_identity)/COUNT(*),4) AS has_identity_pct,
               COUNT_IF(has_identity) AS has_identity_rows,
               ROUND(AVG(is_fraud),6) AS fraud_rate, SUM(is_fraud) AS fraud_rows,
               COUNT(*) AS total_rows FROM MARTS.FCT_TRANSACTIONS""")
    R.table(cov); R()
    hip, fr = float(cov["HAS_IDENTITY_PCT"].iloc[0]), float(cov["FRAUD_RATE"].iloc[0])
    R(f"has_identity = {hip}%, expected 24.4% -> **{'PASS' if abs(hip-24.4) < 0.1 else 'FAIL'}**")
    R(f"fraud rate = {fr:.6f}, expected 0.034990 -> "
      f"**{'PASS' if abs(fr-0.034990) < 5e-6 else 'FAIL'}**")
    if abs(hip - 24.4) >= 0.1:
        flags.append(f"has_identity {hip}")
    if abs(fr - 0.034990) >= 5e-6:
        flags.append(f"fraud rate {fr}")
    R()

    R("### Transaction id reconciliation, raw vs fct"); R()
    rec = q(cur, """
        SELECT (SELECT COUNT(*) FROM RAW.RAW_TRANSACTIONS r WHERE NOT EXISTS
                 (SELECT 1 FROM MARTS.FCT_TRANSACTIONS f WHERE f.transaction_id=r."TransactionID"))
               AS in_raw_not_in_fct,
               (SELECT COUNT(*) FROM MARTS.FCT_TRANSACTIONS f WHERE NOT EXISTS
                 (SELECT 1 FROM RAW.RAW_TRANSACTIONS r WHERE r."TransactionID"=f.transaction_id))
               AS in_fct_not_in_raw""")
    R.table(rec); R()
    a, b = int(rec.iloc[0, 0]), int(rec.iloc[0, 1])
    R(f"in raw not in fct = {a}, in fct not in raw = {b} -> "
      f"**{'PASS' if a == b == 0 else 'FAIL'}**")
    if a or b:
        flags.append(f"id reconciliation {a}/{b}")
    R()

    R("### Backward-looking window inspection, 3 sampled accounts"); R()
    R("`expected_*` columns are recomputed independently in pandas from strictly "
      "earlier rows and compared against what Snowflake produced."); R()
    accts = q(cur, """SELECT account_id FROM MARTS.DIM_ACCOUNTS WHERE txn_count >= 5
                      ORDER BY HASH(account_id) LIMIT 3""")["ACCOUNT_ID"].tolist()
    all_ok = True
    for acct in accts:
        seq = q(cur, f"""
            SELECT transaction_id, transaction_dt, transaction_amt, prior_txn_count,
                   prior_amt_sum, prior_amt_mean, txn_count_1h, txn_count_24h,
                   txn_count_7d, seconds_since_prev_txn
            FROM MARTS.FCT_TRANSACTIONS WHERE account_id = '{acct}'
            ORDER BY transaction_dt, transaction_id""")
        seq.columns = [c.lower() for c in seq.columns]
        for c in seq.columns:
            seq[c] = pd.to_numeric(seq[c], errors="coerce")
        exp_cnt, exp_sum = [], []
        for i in range(len(seq)):
            prior = seq[seq.transaction_dt < seq.transaction_dt.iloc[i]]
            exp_cnt.append(len(prior))
            exp_sum.append(round(float(prior.transaction_amt.sum()), 3) if len(prior) else None)
        seq["expected_prior_count"], seq["expected_prior_sum"] = exp_cnt, exp_sum
        norm = lambda v: [None if x is None or pd.isna(x) else round(float(x), 3) for x in v]
        match = (seq.prior_txn_count.astype(int).tolist() == exp_cnt
                 and norm(seq.prior_amt_sum) == norm(seq["expected_prior_sum"]))
        all_ok &= match
        R(f"**account_id = `{acct}`**, {len(seq)} transactions, "
          f"independent recomputation {'MATCHES' if match else 'DIFFERS'}"); R()
        R.table(seq); R()
    if all_ok:
        R("All three match. Row N reflects rows 1..N-1 only.")
    else:
        R("**FLAG: recomputation disagrees with Snowflake.**")
        flags.append("window recomputation mismatch")
    R()
    R("### Part 1 flags"); R()
    for f in flags:
        R(f"- **{f}**")
    if not flags:
        R("None. Every Part 1 check passed.")
    R()
    R.write()
    conn.close()
    return 1 if flags else 0


# --------------------------------------------------------------------------- #
# train
# --------------------------------------------------------------------------- #

def fetch():
    if core.FCT.exists():
        print(f"reading cached {core.FCT}")
        return pd.read_parquet(core.FCT)
    conn = core.connect()
    cur = conn.cursor()
    print("pulling FCT_TRANSACTIONS...")
    cur.execute("SELECT * FROM MARTS.FCT_TRANSACTIONS")

    # 443 columns x 590k rows does not fit comfortably in 8 GB as float64, so
    # stream arrow batches to parquet, narrowing types on the way.
    import pyarrow as pa
    import pyarrow.parquet as pq

    def shrink(t):
        if pa.types.is_float64(t):
            return pa.float32()
        if pa.types.is_decimal(t):
            return pa.int64() if t.scale == 0 else pa.float64()
        return t

    core.DATA.mkdir(parents=True, exist_ok=True)
    writer, n = None, 0
    for batch in cur.fetch_arrow_batches():
        tbl = batch if isinstance(batch, pa.Table) else pa.Table.from_batches([batch])
        schema = pa.schema([pa.field(f.name.lower(), shrink(f.type)) for f in tbl.schema])
        tbl = tbl.rename_columns([c.lower() for c in tbl.schema.names]).cast(schema)
        if writer is None:
            writer = pq.ParquetWriter(core.FCT, schema, compression="snappy")
        writer.write_table(tbl)
        n += tbl.num_rows
    writer.close()
    conn.close()
    print(f"cached {n:,} rows to {core.FCT}")
    return pd.read_parquet(core.FCT)


def reliability_plot(y, p_raw, p_cal, path):
    fig, ax = plt.subplots(figsize=(7.2, 5.6), facecolor=SURFACE)
    ax.plot([0, 1], [0, 1], color=GRIDC, lw=2, ls="--", zorder=1)
    ax.annotate("perfect calibration", xy=(0.25, 0.25), xytext=(-10, 8),
                textcoords="offset points", ha="right", va="bottom",
                color=INK_2, fontsize=9)
    for p, color, label in ((p_raw, C_BEFORE, "before calibration"),
                            (p_cal, C_AFTER, "after isotonic")):
        ft, mp = calibration_curve(y, p, n_bins=10, strategy="quantile")
        ax.plot(mp, ft, color=color, lw=2, marker="o", ms=8, label=label,
                markeredgecolor=SURFACE, markeredgewidth=2, zorder=3)
    lo = min(p_raw.min(), p_cal.min())
    ax.set_xscale("log"); ax.set_yscale("log")
    ax.set_xlim(max(lo, 1e-4), 1.0); ax.set_ylim(max(lo, 1e-4), 1.0)
    style(ax, "Reliability on the test split (log-log, quantile bins)",
          "mean predicted probability", "observed fraud rate")
    leg = ax.legend(frameon=False, fontsize=9.5, loc="upper left")
    for t in leg.get_texts():
        t.set_color(INK_2)
    fig.tight_layout(); fig.savefig(path, dpi=170, facecolor=SURFACE)
    print(f"wrote {path}")


def train():
    R = Report(VERIFY_MD)
    MODELS.mkdir(exist_ok=True); REPORTS.mkdir(exist_ok=True)
    df = fetch()
    df.columns = [c.lower() for c in df.columns]

    R(); R("## Part 2: the model"); R(); R("### Time splits"); R()
    R("Four disjoint windows, so early stopping and calibration never share data."); R()
    tr = df[df.txn_day < core.TRAIN_MAX_DAY]
    es = df[(df.txn_day >= core.TRAIN_MAX_DAY) & (df.txn_day < core.ES_MAX_DAY)]
    ca = df[(df.txn_day >= core.ES_MAX_DAY) & (df.txn_day < core.CAL_MAX_DAY)]
    te = df[df.txn_day >= core.CAL_MAX_DAY]
    rows = []
    for name, part, rng in (("train", tr, f"txn_day < {core.TRAIN_MAX_DAY}"),
                            ("early stopping", es, f"{core.TRAIN_MAX_DAY} <= txn_day < {core.ES_MAX_DAY}"),
                            ("calibration", ca, f"{core.ES_MAX_DAY} <= txn_day < {core.CAL_MAX_DAY}"),
                            ("test", te, f"txn_day >= {core.CAL_MAX_DAY}")):
        f = part.is_fraud.mean()
        rows.append({"split": name, "day_range": rng, "rows": len(part),
                     "fraud": int(part.is_fraud.sum()), "fraud_rate": round(f, 6),
                     "dev_vs_0.0350_pct": round((f - 0.034990) / 0.034990 * 100, 2)})
    sp = pd.DataFrame(rows)
    R.table(sp); R()
    drift = sp[sp["dev_vs_0.0350_pct"].abs() > 30]
    R(f"**FLAG: {len(drift)} split(s) deviate more than 30% from 0.0350.**" if len(drift)
      else "No split deviates more than 30% from the 0.0350 base rate.")
    R(); R(f"Total across splits: {len(tr)+len(es)+len(ca)+len(te):,} of {len(df):,} rows."); R()

    feats = [c for c in df.columns if c not in EXCLUDE]
    X, cats = core.encode(df[feats])
    sel_path = MODELS / "selected_features.json"
    if sel_path.exists():
        sel = json.loads(sel_path.read_text())
        feats = [f for f in sel["features"] if f in X.columns]
        cats = [c for c in cats if c in feats]
        X = X[feats]
        print(f"using pruned feature set: {sel['variant']}, {len(feats)} features")
    y = df.is_fraud.astype("int8")
    Xtr, Xes, Xca, Xte = X.loc[tr.index], X.loc[es.index], X.loc[ca.index], X.loc[te.index]
    ytr, yes_, yca, yte = y.loc[tr.index], y.loc[es.index], y.loc[ca.index], y.loc[te.index]
    del X

    R("### Features"); R()
    R(f"Features used: **{len(feats)}** ({len(cats)} categorical, "
      f"{len(feats)-len(cats)} numeric)."); R()
    leaked = [c for c in ("transaction_id", "account_id", "txn_day", "transaction_dt")
              if c in feats]
    R(f"Excluded by design: {sorted(EXCLUDE)}"); R()
    R(f"Identifier/time columns in the feature list: {leaked or 'none'} -> "
      f"**{'FAIL' if leaked else 'PASS'}**"); R()

    clf = lgb.LGBMClassifier(**core.LGB_PARAMS)
    clf.fit(Xtr, ytr, eval_set=[(Xes, yes_)], eval_metric="average_precision",
            categorical_feature=cats,
            callbacks=[lgb.early_stopping(100, verbose=False), lgb.log_evaluation(0)])
    R(f"Best iteration on the early stopping split (days {core.TRAIN_MAX_DAY}-"
      f"{core.ES_MAX_DAY-1}): **{clf.best_iteration_}** of 3000, patience 100."); R()

    # Fitted on days 130-149, which the model saw during neither training nor
    # early stopping.
    cal = CalibratedClassifierCV(FrozenEstimator(clf), method="isotonic")
    cal.fit(Xca, yca)
    p_tr = clf.predict_proba(Xtr)[:, 1]
    p_raw, p_cal = clf.predict_proba(Xte)[:, 1], cal.predict_proba(Xte)[:, 1]

    m = {"train_pr_auc": average_precision_score(ytr, p_tr),
         "test_pr_auc_raw": average_precision_score(yte, p_raw),
         "test_pr_auc_cal": average_precision_score(yte, p_cal),
         "test_roc_auc_raw": roc_auc_score(yte, p_raw),
         "test_roc_auc_cal": roc_auc_score(yte, p_cal),
         "test_brier_raw": brier_score_loss(yte, p_raw),
         "test_brier_cal": brier_score_loss(yte, p_cal)}
    R("### Test metrics"); R(); R.block(pd.Series(m).round(6).to_string()); R()
    gap = m["train_pr_auc"] - m["test_pr_auc_raw"]
    R(f"Train PR-AUC {m['train_pr_auc']:.4f} vs test {m['test_pr_auc_raw']:.4f}, "
      f"gap {gap:+.4f}.")
    R(f"Test PR-AUC {m['test_pr_auc_raw']:.4f} is "
      f"{'above' if m['test_pr_auc_raw'] > 0.85 else 'below'} the 0.85 suspicion threshold.")
    if gap > 0.15:
        R(f"**FLAG: train/test PR-AUC gap {gap:.4f} suggests overfitting.** "
          "Attacking it directly made the model worse; see "
          "reports/improvements_summary.md.")
    R()
    delta = m["test_brier_raw"] - m["test_brier_cal"]
    R(f"Brier {'improved' if delta > 0 else 'degraded'} under calibration: "
      f"{m['test_brier_raw']:.6f} -> {m['test_brier_cal']:.6f} "
      f"({delta/m['test_brier_raw']*100:+.2f}%).")
    if delta <= 0:
        R(); R("**FLAG: isotonic did not improve Brier on test.** The remaining "
               "cause is drift between the calibration and test periods.")
    R()

    R("### Full 437 vs this run, side by side"); R()
    cmp = pd.DataFrame([
        {"metric": "features", "stage_1": BASELINE["n_features"], "this_run": len(feats)},
        {"metric": "train PR-AUC", "stage_1": BASELINE["train_pr_auc"], "this_run": m["train_pr_auc"]},
        {"metric": "test PR-AUC (raw)", "stage_1": BASELINE["test_pr_auc_raw"], "this_run": m["test_pr_auc_raw"]},
        {"metric": "test PR-AUC (cal)", "stage_1": BASELINE["test_pr_auc_cal"], "this_run": m["test_pr_auc_cal"]},
        {"metric": "test ROC-AUC (raw)", "stage_1": BASELINE["test_roc_auc_raw"], "this_run": m["test_roc_auc_raw"]},
        {"metric": "test Brier (raw)", "stage_1": BASELINE["test_brier_raw"], "this_run": m["test_brier_raw"]},
        {"metric": "test Brier (cal)", "stage_1": BASELINE["test_brier_cal"], "this_run": m["test_brier_cal"]},
        {"metric": "train/test gap", "stage_1": BASELINE["train_pr_auc"] - BASELINE["test_pr_auc_raw"], "this_run": gap}])
    cmp["delta"] = cmp.this_run - cmp.stage_1
    R.table(cmp.round(6)); R()
    R("Both runs use identical splits, so this comparison is clean."); R()

    imp = pd.DataFrame({"feature": feats, "gain": clf.booster_.feature_importance("gain")})
    imp["pct_of_total_gain"] = imp.gain / imp.gain.sum() * 100
    imp = imp.sort_values("gain", ascending=False).reset_index(drop=True)
    R("### Top 25 features by gain"); R(); R.table(imp.head(25).round(4)); R()
    top = imp.iloc[0]
    R(f"{'**FLAG: ' if top.pct_of_total_gain > 30 else 'No single feature dominates: '}"
      f"`{top.feature}` carries {top.pct_of_total_gain:.2f}% of total gain"
      f"{', above the 30% dominance threshold.**' if top.pct_of_total_gain > 30 else ', below the 30% threshold.'}")
    R()

    R("### Predicted probability distribution on test"); R()
    dist = pd.DataFrame({
        "statistic": ["min", "p25", "median", "p75", "p95", "max", "mean"],
        "raw": [p_raw.min(), *np.quantile(p_raw, [.25, .5, .75, .95]), p_raw.max(), p_raw.mean()],
        "calibrated": [p_cal.min(), *np.quantile(p_cal, [.25, .5, .75, .95]), p_cal.max(), p_cal.mean()]})
    R.table(dist.round(6)); R()
    R(f"Actual test fraud rate: {yte.mean():.6f}. Mean calibrated probability: "
      f"{p_cal.mean():.6f} (difference {p_cal.mean()-yte.mean():+.6f})."); R()

    R("### Decile calibration, predicted vs actual"); R()
    for label, p in (("before calibration", p_raw), ("after isotonic", p_cal)):
        d = pd.DataFrame({"p": p, "y": yte.values})
        d["decile"] = pd.qcut(d.p.rank(method="first"), 10, labels=range(1, 11))
        g = d.groupby("decile", observed=True).agg(
            n=("y", "size"), predicted=("p", "mean"), actual=("y", "mean")).reset_index()
        g["abs_diff"] = (g.predicted - g.actual).abs()
        R(f"**{label}**"); R(); R.table(g.round(6)); R()

    reliability_plot(yte.values, p_raw, p_cal, REPORTS / "calibration_curve.png")
    R("Reliability curve: `reports/calibration_curve.png`."); R()

    joblib.dump(clf, MODELS / "lgbm_fraud_model.joblib")
    joblib.dump(cal, MODELS / "isotonic_calibrator.joblib")
    clf.booster_.save_model(str(MODELS / "lgbm_fraud_model.txt"))
    (MODELS / "model_metadata.json").write_text(json.dumps(
        {"best_iteration": int(clf.best_iteration_), "n_features": len(feats),
         "categorical_features": cats, "features": feats,
         "splits": {"train_max_day": core.TRAIN_MAX_DAY, "es_max_day": core.ES_MAX_DAY,
                    "cal_max_day": core.CAL_MAX_DAY},
         "metrics": {k: float(v) for k, v in m.items()}, "seed": core.SEED}, indent=2))
    R("Saved to `models/`: lgbm_fraud_model.joblib, isotonic_calibrator.joblib, "
      "lgbm_fraud_model.txt, model_metadata.json."); R()

    np.save(REPORTS / "_test_probs.npy", p_cal)
    np.save(REPORTS / "_test_probs_raw.npy", p_raw)
    te[["transaction_id", "transaction_amt", "is_fraud", "txn_day"]].to_parquet(
        REPORTS / "_test_frame.parquet", index=False)
    R.write(mode="a")


# --------------------------------------------------------------------------- #
# decide
# --------------------------------------------------------------------------- #

BASELINE_DECISION = {"threshold": 0.101064, "cost_opt": 296570.28, "cost_naive": 441084.71,
                     "cost_approve_all": 577294.40, "cost_decline_all": 1414894.91,
                     "fp": 5734, "tp": 2139, "precision": 0.271688, "recall": 0.651737,
                     "fdr": 0.062767, "fraud_dollars_caught": 328658.31}


def decide():
    R = Report(VERIFY_MD)
    p = np.load(REPORTS / "_test_probs.npy")
    te = pd.read_parquet(REPORTS / "_test_frame.parquet")
    y = te.is_fraud.to_numpy().astype(int)
    amt = te.transaction_amt.to_numpy().astype(float)

    R(); R("## Part 3: the decision layer"); R(); R("### Cost assumptions"); R()
    R("**Assumptions, not measured facts.** IEEE-CIS has no chargeback, margin or "
      "churn data. Sensitivity is characterised in `reports/cost_sensitivity.md`."); R()
    R.block(json.dumps(COSTS, indent=2)); R()
    R("| Outcome | Cost |"); R("| --- | --- |")
    R("| fraud approved (FN) | transaction amount + $25 chargeback fee |")
    R("| legit declined (FP) | 2.5% margin lost + 5% x $200 churn + $2 review |")
    R("| fraud declined (TP) | $2 review |")
    R("| legit approved (TN) | $0 |"); R()

    t_opt, c_opt, costs = core.sweep(p, y, amt)
    c_naive = core.cost_at(0.5, p, y, amt)
    c_approve = core.cost_at(1.01, p, y, amt)
    c_decline = core.cost_at(0.0, p, y, amt)
    total_dollars, fraud_dollars = amt.sum(), amt[y == 1].sum()

    R("### Threshold sweep"); R()
    R(f"Swept {len(core.THRESHOLD_GRID):,} thresholds from 0.001 to 0.99."); R()
    R(f"**Chosen threshold: {t_opt:.6f}**"); R()
    sw = pd.DataFrame([
        {"policy": "optimum", "threshold": round(t_opt, 6), "total_cost_usd": round(c_opt, 2)},
        {"policy": "naive 0.5", "threshold": 0.5, "total_cost_usd": round(c_naive, 2)},
        {"policy": "approve everything", "threshold": float("inf"), "total_cost_usd": round(c_approve, 2)},
        {"policy": "decline everything", "threshold": 0.0, "total_cost_usd": round(c_decline, 2)}])
    sw["vs_optimum_usd"] = (sw.total_cost_usd - c_opt).round(2)
    R.table(sw); R()

    R("### Sensitivity to the threshold"); R()
    sens = pd.DataFrame([
        {"threshold": round(t, 6), "label": lab, "total_cost_usd": round(core.cost_at(t, p, y, amt), 2)}
        for t, lab in ((t_opt * 0.8, "optimum -20%"), (t_opt, "optimum"), (t_opt * 1.2, "optimum +20%"))])
    sens["delta_vs_optimum_usd"] = (sens.total_cost_usd - c_opt).round(2)
    sens["delta_pct"] = (sens.delta_vs_optimum_usd / c_opt * 100).round(3)
    R.table(sens); R()
    worst = sens.delta_pct.abs().max()
    R(f"Moving the threshold 20% either way changes total cost by at most {worst:.3f}%. "
      "The direction of this asymmetry has flipped between model versions that "
      "cannot be told apart on cost, so it should not be treated as a finding."); R()

    o = core.confusion(t_opt, p, y)
    n = core.confusion(0.5, p, y)
    R("### Confusion matrices, raw counts"); R()
    cm = pd.DataFrame([o, n]); cm.insert(0, "policy", ["optimum", "naive 0.5"])
    R.table(cm.round(6)); R()

    R("### Fraud dollars"); R()
    caught_opt = amt[(p >= t_opt) & (y == 1)].sum()
    caught_naive = amt[(p >= 0.5) & (y == 1)].sum()
    dollars = pd.DataFrame([
        {"metric": "total transaction dollars in test", "usd": round(total_dollars, 2)},
        {"metric": "total fraud dollars in test", "usd": round(fraud_dollars, 2)},
        {"metric": "fraud dollars caught at optimum", "usd": round(caught_opt, 2)},
        {"metric": "fraud dollars caught at 0.5", "usd": round(caught_naive, 2)}])
    dollars["pct_of_fraud_dollars"] = (dollars.usd / fraud_dollars * 100).round(3)
    R.table(dollars); R()
    R(f"Share of fraud dollars caught at the chosen threshold: "
      f"**{caught_opt/fraud_dollars*100:.2f}%**"); R()

    R("### Reconciling the extremes"); R()
    n_all, n_fraud = len(y), int((y == 1).sum())
    n_legit, legit_dollars = n_all - n_fraud, amt[y == 0].sum()
    dm = COSTS["margin_rate"] * legit_dollars
    dc = COSTS["churn_prob_after_false_decline"] * COSTS["account_lifetime_value_usd"] * n_legit
    dr = COSTS["manual_review_cost_usd"] * n_all
    R(f"**Decline everything**: FN = 0, TP = all {n_fraud:,}, FP = all {n_legit:,}."); R()
    R.block(f"lost margin  0.025 x ${legit_dollars:,.2f} = ${dm:>13,.2f}\n"
            f"churn        0.05 x $200 x {n_legit:,}    = ${dc:>13,.2f}\n"
            f"review       $2 x {n_all:,} declines      = ${dr:>13,.2f}\n"
            f"fraud loss   every fraud declined         = ${0:>13,.2f}\n"
            f"{'-'*52}\nTOTAL                              = ${dm+dc+dr:>13,.2f}\n"
            f"computed by cost_at(0.0)           = ${c_decline:>13,.2f}"); R()
    R(f"Margin plus churn alone is ${dm+dc:,.2f}. The remaining ${dr:,.2f} is the "
      f"review term: declining everything means reviewing all {n_all:,} transactions."); R()
    am = amt[y == 1].sum(); ac = COSTS["chargeback_fee_usd"] * n_fraud
    R(f"**Approve everything**: TP = FP = 0, FN = all {n_fraud:,}."); R()
    R.block(f"fraud loss   ${am:,.2f} of goods = ${am:>13,.2f}\n"
            f"chargebacks  $25 x {n_fraud:,}       = ${ac:>13,.2f}\n"
            f"{'-'*52}\nTOTAL                       = ${am+ac:>13,.2f}\n"
            f"computed by cost_at(1.01)   = ${c_approve:>13,.2f}"); R()

    R("### Previous run vs this run, decision layer"); R()
    B = BASELINE_DECISION
    cmp = pd.DataFrame([
        {"metric": "chosen threshold", "previous": B["threshold"], "this_run": round(t_opt, 6)},
        {"metric": "total cost at optimum", "previous": B["cost_opt"], "this_run": round(c_opt, 2)},
        {"metric": "saving vs 0.5", "previous": round(B["cost_naive"] - B["cost_opt"], 2), "this_run": round(c_naive - c_opt, 2)},
        {"metric": "false decline rate", "previous": B["fdr"], "this_run": round(o["false_decline_rate"], 6)},
        {"metric": "precision", "previous": B["precision"], "this_run": round(o["precision"], 6)},
        {"metric": "recall", "previous": B["recall"], "this_run": round(o["recall"], 6)},
        {"metric": "fraud dollars caught", "previous": B["fraud_dollars_caught"], "this_run": round(caught_opt, 2)}])
    cmp["delta"] = (cmp.this_run - cmp.previous).round(6)
    R.table(cmp); R()

    fig, ax = plt.subplots(figsize=(8.4, 5.4), facecolor=SURFACE)
    ax.plot(core.THRESHOLD_GRID, costs / 1000, color="#2a78d6", lw=2, zorder=3)
    # The 0.5 marker sits near the right edge, so its label anchors inward.
    for t, c, color, lab, dx, ha in ((t_opt, c_opt, C_OPT, f"optimum {t_opt:.3f}", 8, "left"),
                                     (0.5, c_naive, C_NAIVE, "naive 0.5", -8, "right")):
        ax.axvline(t, color=color, lw=2, ls="--", zorder=2)
        ax.plot([t], [c / 1000], marker="o", ms=9, color=color,
                markeredgecolor=SURFACE, markeredgewidth=2, zorder=4)
        ax.annotate(f"{lab}\n${c/1000:,.1f}k", xy=(t, c / 1000), xytext=(dx, 16),
                    textcoords="offset points", ha=ha, color=INK_2, fontsize=9, weight="bold")
    ax.set_xscale("log")
    style(ax, "Cost against decline threshold",
          "decline threshold (calibrated probability, log scale)",
          "total cost on test split (thousands USD)")
    fig.tight_layout(); fig.savefig(REPORTS / "cost_vs_threshold.png", dpi=170, facecolor=SURFACE)
    R("Cost curve: `reports/cost_vs_threshold.png`."); R()
    R.write(mode="a")

    meta = json.loads((MODELS / "model_metadata.json").read_text())["metrics"]
    RESULTS_MD.write_text(f"""# Stage 1 results

Evaluated on a held-out time split (txn_day >= 150, {len(te):,} transactions,
{n_fraud:,} fraudulent).

## Headline

At a decline threshold of **{t_opt:.4f}**, the model prevents **${caught_opt:,.0f}**
of the **${fraud_dollars:,.0f}** of fraud in the test split
({caught_opt/fraud_dollars*100:.1f}%), while declining **{o['fp']:,}** legitimate
transactions ({o['false_decline_rate']*100:.2f}% of legitimate traffic).

Total modelled cost is **${c_opt:,.0f}**, against **${c_naive:,.0f}** at the naive
0.5 cutoff and **${c_approve:,.0f}** if every transaction is approved.

| Policy | Total cost | Saving vs this policy |
| --- | --- | --- |
| Chosen threshold {t_opt:.4f} | ${c_opt:,.0f} | - |
| Naive 0.5 cutoff | ${c_naive:,.0f} | ${c_naive-c_opt:,.0f} |
| Approve everything | ${c_approve:,.0f} | ${c_approve-c_opt:,.0f} |
| Decline everything | ${c_decline:,.0f} | ${c_decline-c_opt:,.0f} |

## Decision quality

| Metric | At {t_opt:.4f} | At 0.50 |
| --- | --- | --- |
| True positives | {o['tp']:,} | {n['tp']:,} |
| False positives | {o['fp']:,} | {n['fp']:,} |
| False negatives | {o['fn']:,} | {n['fn']:,} |
| True negatives | {o['tn']:,} | {n['tn']:,} |
| Precision | {o['precision']:.4f} | {n['precision']:.4f} |
| Recall | {o['recall']:.4f} | {n['recall']:.4f} |
| False decline rate | {o['false_decline_rate']*100:.3f}% | {n['false_decline_rate']*100:.3f}% |

## Model quality

| Metric | Value |
| --- | --- |
| PR-AUC (test, raw) | {meta['test_pr_auc_raw']:.4f} |
| PR-AUC (test, calibrated) | {meta['test_pr_auc_cal']:.4f} |
| ROC-AUC (test) | {meta['test_roc_auc_raw']:.4f} |
| Brier (test, raw) | {meta['test_brier_raw']:.6f} |
| Brier (test, calibrated) | {meta['test_brier_cal']:.6f} |

## Cost assumptions

Assumptions, not measurements.

| Assumption | Value |
| --- | --- |
| Chargeback fee | $25.00 |
| Margin rate | 2.5% |
| Churn probability after a false decline | 5% |
| Account lifetime value | $200.00 |
| Manual review cost | $2.00 |

Sensitivity: moving the threshold 20% either way changes total cost by at most
{worst:.3f}%. Full surface in `cost_sensitivity.md`.

Charts: `cost_vs_threshold.png`, `calibration_curve.png`.
""")
    print(f"wrote {RESULTS_MD}")


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "all"
    if cmd == "all":
        verify(); train(); decide()
    else:
        sys.exit({"verify": verify, "train": train, "decide": decide}[cmd]() or 0)
