"""Part 1 verification. Prints every number and appends to reports/verification.md."""

import os
import sys
from pathlib import Path

import pandas as pd
import snowflake.connector
from dotenv import load_dotenv

OUT = Path("reports/verification.md")
buf = []


def emit(line=""):
    print(line)
    buf.append(line)


def table(df, floatfmt=None):
    s = df.to_string(index=False)
    emit("```")
    emit(s)
    emit("```")


def q(cur, sql):
    cur.execute(sql)
    cols = [d[0] for d in cur.description]
    return pd.DataFrame(cur.fetchall(), columns=cols)


def main():
    load_dotenv(".env")
    conn = snowflake.connector.connect(
        account=os.environ["SNOWFLAKE_ACCOUNT"], user=os.environ["SNOWFLAKE_USER"],
        password=os.environ["SNOWFLAKE_PASSWORD"], role=os.environ["SNOWFLAKE_ROLE"],
        warehouse=os.environ["SNOWFLAKE_WAREHOUSE"], database="FRAUD", schema="MARTS")
    cur = conn.cursor()
    cur.execute("ALTER WAREHOUSE FRAUD_WH RESUME IF SUSPENDED")
    flags = []

    emit("# Stage 1 verification")
    emit()
    emit("Generated by `src/verify_part1.py`, `src/train_model.py`, `src/decision_layer.py`.")
    emit()
    emit("## Part 1: dbt")
    emit()

    # --- row counts -------------------------------------------------------
    emit("### Row counts")
    emit()
    rc = q(cur, """
        SELECT 'fct_transactions' AS model, COUNT(*) AS n_rows FROM MARTS.FCT_TRANSACTIONS
        UNION ALL SELECT 'stg_transactions', COUNT(*) FROM STAGING.STG_TRANSACTIONS
        UNION ALL SELECT 'stg_identity',     COUNT(*) FROM STAGING.STG_IDENTITY
        UNION ALL SELECT 'dim_accounts',     COUNT(*) FROM MARTS.DIM_ACCOUNTS
    """)
    rc["N_ROWS"] = rc["N_ROWS"].astype(int)
    table(rc)
    fct_rows = int(rc.loc[rc.MODEL == "fct_transactions", "N_ROWS"].iloc[0])
    emit()
    ok = fct_rows == 590540
    emit(f"fct_transactions = {fct_rows:,}, expected 590,540 -> **{'PASS' if ok else 'FAIL'}**")
    if not ok:
        flags.append(f"fct_transactions row count {fct_rows} != 590540")
    emit()

    # --- account distribution --------------------------------------------
    emit("### Account proxy: distinct accounts and transactions per account")
    emit()
    ad = q(cur, """
        SELECT COUNT(*) AS distinct_accounts,
               MIN(txn_count) AS min_txns,
               MEDIAN(txn_count) AS median_txns,
               ROUND(AVG(txn_count), 4) AS mean_txns,
               PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY txn_count) AS p95_txns,
               MAX(txn_count) AS max_txns
        FROM MARTS.DIM_ACCOUNTS
    """)
    table(ad.T.reset_index().rename(columns={"index": "metric", 0: "value"}))
    median = float(ad["MEDIAN_TXNS"].iloc[0])
    emit()
    if median <= 1:
        emit(f"**FLAG RAISED: median transactions per account is {median}.**")
        emit()
        emit("Reporting this because it is the tripwire condition, but the "
             "tripwire is measuring the wrong population here. The median "
             "*account* has 1 transaction because 57.5% of accounts are cards "
             "seen exactly once in the 182-day window, which is ordinary for "
             "card data. The median *transaction*, which is what the window "
             "features actually operate on, sits in an account of 5. "
             "78.8% of transactions belong to accounts with more than one "
             "transaction, so the proxy is grouping. Verdict: not a defect, "
             "but the 21.2% of transactions in singleton accounts will never "
             "have prior-window history and the model must tolerate that.")
        flags.append(f"median txns per account = {median} (see interpretation, "
                     "transaction-weighted median is 5)")
    else:
        emit(f"Median is {median}, above 1, so the proxy groups multiple "
             "transactions per account as intended.")
    emit()
    tw = q(cur, """
        SELECT MEDIAN(txn_count) AS txn_weighted_median_account_size,
               ROUND(AVG(txn_count), 4) AS txn_weighted_mean_account_size,
               ROUND(100.0 * COUNT_IF(txn_count > 1) / COUNT(*), 2) AS pct_txns_in_multi_txn_accounts
        FROM MARTS.FCT_TRANSACTIONS f
        JOIN MARTS.DIM_ACCOUNTS d USING (account_id)
    """)
    emit("Weighted by transaction rather than by account, which is the view "
         "that matters for whether the window features have any history to "
         "work with:")
    emit()
    table(tw.T.reset_index().rename(columns={"index": "metric", 0: "value"}))
    emit()
    emit("Transactions-per-account histogram:")
    emit()
    hist = q(cur, """
        SELECT CASE WHEN txn_count = 1 THEN '1'
                    WHEN txn_count BETWEEN 2 AND 4 THEN '2-4'
                    WHEN txn_count BETWEEN 5 AND 9 THEN '5-9'
                    WHEN txn_count BETWEEN 10 AND 49 THEN '10-49'
                    ELSE '50+' END AS bucket,
               COUNT(*) AS accounts,
               SUM(txn_count) AS transactions
        FROM MARTS.DIM_ACCOUNTS GROUP BY 1
        ORDER BY MIN(txn_count)
    """)
    hist["PCT_ACCOUNTS"] = (hist.ACCOUNTS / hist.ACCOUNTS.sum() * 100).round(2)
    hist["PCT_TRANSACTIONS"] = (hist.TRANSACTIONS / hist.TRANSACTIONS.sum() * 100).round(2)
    table(hist)
    emit()

    # --- degraded keys ----------------------------------------------------
    emit("### Degraded account keys")
    emit()
    dg = q(cur, """
        SELECT account_key_tier, COUNT(*) AS n_rows,
               ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 4) AS pct
        FROM MARTS.FCT_TRANSACTIONS GROUP BY 1 ORDER BY 2 DESC
    """)
    table(dg)
    deg = q(cur, """
        SELECT COUNT_IF(is_degraded_key) AS degraded_n_rows,
               ROUND(100.0 * COUNT_IF(is_degraded_key) / COUNT(*), 4) AS degraded_pct
        FROM MARTS.FCT_TRANSACTIONS
    """)
    table(deg)
    emit()

    # --- null rates -------------------------------------------------------
    emit("### Null rate, every engineered feature")
    emit()
    feats = ["log_amount", "prior_txn_count", "prior_amt_sum", "prior_amt_mean",
             "txn_count_1h", "txn_count_24h", "txn_count_7d",
             "prev_transaction_dt", "seconds_since_prev_txn",
             "amt_to_prior_mean_ratio", "txn_hour", "txn_dow", "has_identity",
             "account_id", "is_degraded_key"]
    sel = ",\n".join(
        f"ROUND(100.0 * COUNT_IF({f} IS NULL) / COUNT(*), 4) AS {f}" for f in feats)
    nr = q(cur, f"SELECT {sel} FROM MARTS.FCT_TRANSACTIONS")
    nrt = nr.T.reset_index()
    nrt.columns = ["feature", "null_pct"]
    nrt["null_pct"] = nrt["null_pct"].astype(float)
    nrt["flag"] = nrt["null_pct"].apply(lambda v: "OVER 50%" if v > 50 else "")
    table(nrt)
    over = nrt[nrt.null_pct > 50]
    emit()
    if len(over):
        emit(f"**FLAG: {len(over)} feature(s) above 50% null: "
             f"{', '.join(over.feature)}**")
        flags.append(f"features over 50% null: {list(over.feature)}")
    else:
        emit("No engineered feature exceeds 50% null.")
    emit()
    emit("The prior-window features are null for the first transaction of each "
         "account, which is 217,850 of 590,540 rows (36.89%). That is the "
         "correct behaviour for a strictly backward-looking window, not a defect.")
    emit()

    # --- identity coverage and fraud rate ---------------------------------
    emit("### Identity coverage and fraud rate")
    emit()
    cov = q(cur, """
        SELECT ROUND(100.0 * COUNT_IF(has_identity) / COUNT(*), 4) AS has_identity_pct,
               COUNT_IF(has_identity) AS has_identity_rows,
               ROUND(AVG(is_fraud), 6) AS fraud_rate,
               SUM(is_fraud) AS fraud_rows,
               COUNT(*) AS total_rows
        FROM MARTS.FCT_TRANSACTIONS
    """)
    table(cov)
    hip = float(cov["HAS_IDENTITY_PCT"].iloc[0])
    fr = float(cov["FRAUD_RATE"].iloc[0])
    emit()
    emit(f"has_identity true rate = {hip}%, expected 24.4% -> "
         f"**{'PASS' if abs(hip - 24.4) < 0.1 else 'FAIL'}**")
    emit(f"fraud rate = {fr:.6f}, expected 0.034990 -> "
         f"**{'PASS' if abs(fr - 0.034990) < 5e-6 else 'FAIL'}**")
    if abs(hip - 24.4) >= 0.1:
        flags.append(f"has_identity rate {hip} != 24.4")
    if abs(fr - 0.034990) >= 5e-6:
        flags.append(f"fraud rate {fr} != 0.034990")
    emit()

    # --- id reconciliation -------------------------------------------------
    emit("### Transaction id reconciliation, raw vs fct")
    emit()
    rec = q(cur, """
        SELECT
          (SELECT COUNT(*) FROM RAW.RAW_TRANSACTIONS r
             WHERE NOT EXISTS (SELECT 1 FROM MARTS.FCT_TRANSACTIONS f
                               WHERE f.transaction_id = r."TransactionID")) AS in_raw_not_in_fct,
          (SELECT COUNT(*) FROM MARTS.FCT_TRANSACTIONS f
             WHERE NOT EXISTS (SELECT 1 FROM RAW.RAW_TRANSACTIONS r
                               WHERE r."TransactionID" = f.transaction_id)) AS in_fct_not_in_raw
    """)
    table(rec)
    a, b = int(rec.iloc[0, 0]), int(rec.iloc[0, 1])
    emit()
    emit(f"in raw not in fct = {a}, in fct not in raw = {b} -> "
         f"**{'PASS' if a == 0 and b == 0 else 'FAIL'}**")
    if a or b:
        flags.append(f"id reconciliation {a}/{b}")
    emit()

    # --- window inspection -------------------------------------------------
    emit("### Backward-looking window inspection, 3 sampled accounts")
    emit()
    emit("Three accounts with 5 or more transactions, sampled with a fixed seed. "
         "For each, `expected_prior_count` and `expected_prior_sum` are "
         "recomputed independently in pandas from strictly earlier rows and "
         "compared to what Snowflake produced.")
    emit()
    accts = q(cur, """
        SELECT account_id FROM MARTS.DIM_ACCOUNTS
        WHERE txn_count >= 5 ORDER BY HASH(account_id) LIMIT 3
    """)["ACCOUNT_ID"].tolist()

    all_ok = True
    for acct in accts:
        seq = q(cur, f"""
            SELECT transaction_id, transaction_dt, transaction_amt,
                   prior_txn_count, prior_amt_sum, prior_amt_mean,
                   txn_count_1h, txn_count_24h, txn_count_7d,
                   seconds_since_prev_txn
            FROM MARTS.FCT_TRANSACTIONS
            WHERE account_id = '{acct}'
            ORDER BY transaction_dt, transaction_id
        """)
        seq.columns = [c.lower() for c in seq.columns]
        for c in seq.columns:
            seq[c] = pd.to_numeric(seq[c], errors="coerce")
        exp_cnt, exp_sum = [], []
        for i in range(len(seq)):
            prior = seq[seq.transaction_dt < seq.transaction_dt.iloc[i]]
            exp_cnt.append(len(prior))
            exp_sum.append(float(prior.transaction_amt.sum()) if len(prior) else None)
        seq["expected_prior_count"] = exp_cnt
        seq["expected_prior_sum"] = [None if v is None else round(v, 3) for v in exp_sum]
        # Normalise None/NaN to a single sentinel so the comparison is not
        # defeated by NaN != NaN or None != NaN.
        def norm(vals):
            return [None if v is None or pd.isna(v) else round(float(v), 3) for v in vals]

        got_cnt = seq.prior_txn_count.astype(int).tolist()
        match = (got_cnt == exp_cnt
                 and norm(seq.prior_amt_sum) == norm(seq["expected_prior_sum"]))
        all_ok &= match
        emit(f"**account_id = `{acct}`**, {len(seq)} transactions, "
             f"independent recomputation {'MATCHES' if match else 'DIFFERS'}")
        emit()
        table(seq)
        emit()
    if all_ok:
        emit("All three accounts match. Row N's window features reflect rows "
             "1..N-1 only. Note the first row of each account has "
             "prior_txn_count = 0 and null prior sums, which is what a frame "
             "ending at `1 PRECEDING` must produce.")
    else:
        emit("**FLAG: independent recomputation disagrees with Snowflake.**")
        flags.append("window recomputation mismatch")
    emit()

    emit("### Part 1 flags")
    emit()
    if flags:
        for f in flags:
            emit(f"- **{f}**")
    else:
        emit("None. Every Part 1 check passed.")
    emit()

    OUT.write_text("\n".join(buf) + "\n")
    print(f"\nwrote {OUT}")
    conn.close()
    return 1 if flags else 0


if __name__ == "__main__":
    sys.exit(main())
